#http://ed.am/posts/using-an-external-editor-for-arduino-development

BOARD = uno
include ../arduino.mk

#To compile type `$ make`

#To upload to arduino: `$ make upload`

#To read serial: `$ make monitor`
# To stop: ctrl+a, k
